[package]
name = "bayard-rest"
version = "0.8.0"
authors = ["Minoru Osuka <minoru.osuka@gmail.com>"]
edition = "2018"
description = "REST API server for Bayard."
documentation = "https://bayard-search.github.io/bayard/"
homepage = "https://github.com/bayard-search"
repository = "https://github.com/bayard-search/bayard/bayard-rest"
readme = "README.md"
keywords = ["full-text", "search", "index", "server", "rest"]
categories = ["database"]
license = "MIT"

[[bin]]
name = "bayard-rest"
path = "src/main.rs"

[dependencies]
actix = "0.9.0"
actix-rt = "1.1.1"
actix-server = "1.0.2"
actix-web = "2.0.0"
clap = "2.33.0"
crossbeam-channel = "0.4.2"
ctrlc = { version = "3.1.4", features = ["termination"] }
log = "0.4.8"
num_cpus = "1.13.0"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
serde_qs = "0.5.2"

bayard-client = { version = "0.8.0", path = "../bayard-client" }
bayard-common = { version = "0.8.0", path = "../bayard-common" }
